# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-25 12:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id_discipl', models.AutoField(primary_key=True, serialize=False)),
                ('name_discipl', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Kafedra',
            fields=[
                ('id_kaf', models.AutoField(primary_key=True, serialize=False)),
                ('name_kaf', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Prepod',
            fields=[
                ('id_prepod', models.AutoField(primary_key=True, serialize=False)),
                ('FIO_prepod', models.CharField(max_length=100)),
                ('Stavka_prepod', models.FloatField(default=0)),
                ('Discipl', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Kursovaya.Disciplina')),
            ],
        ),
    ]
