# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-25 16:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Kursovaya', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id_inst', models.AutoField(primary_key=True, serialize=False)),
                ('name_inst', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Kampus',
            fields=[
                ('id_kampus', models.AutoField(primary_key=True, serialize=False)),
                ('adress_kampus', models.CharField(max_length=100)),
                ('name_kampus', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Kafedra',
        ),
        migrations.RenameField(
            model_name='prepod',
            old_name='Discipl',
            new_name='discipl',
        ),
        migrations.RenameField(
            model_name='prepod',
            old_name='Stavka_prepod',
            new_name='stavka_prepod',
        ),
        migrations.AddField(
            model_name='institute',
            name='kampus_inst',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Kursovaya.Kampus'),
        ),
    ]
