# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-25 16:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Kursovaya', '0002_auto_20180525_1907'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kafedra',
            fields=[
                ('id_kaf', models.AutoField(primary_key=True, serialize=False)),
                ('name_kaf', models.CharField(max_length=100)),
                ('inst', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Kursovaya.Institute')),
            ],
        ),
    ]
