# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-25 16:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Kursovaya', '0003_kafedra'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id_aud', models.AutoField(primary_key=True, serialize=False)),
                ('number_aud', models.IntegerField(default=0)),
                ('mesta', models.IntegerField(default=0)),
                ('kampus_aud', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Kursovaya.Kampus')),
            ],
        ),
    ]
