# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-25 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kursovaya', '0004_auditoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forma_ob',
            fields=[
                ('id_forma', models.AutoField(primary_key=True, serialize=False)),
                ('name_forma', models.CharField(max_length=50)),
            ],
        ),
    ]
