# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-25 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kursovaya', '0005_forma_ob'),
    ]

    operations = [
        migrations.CreateModel(
            name='Napravlenie',
            fields=[
                ('id_napr', models.AutoField(primary_key=True, serialize=False)),
                ('nazv_napr', models.CharField(max_length=50)),
            ],
        ),
    ]
