# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-25 16:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Kursovaya', '0006_napravlenie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uch_plan',
            fields=[
                ('id_uch', models.AutoField(primary_key=True, serialize=False)),
                ('profil', models.CharField(max_length=20)),
                ('vidi_deyat', models.CharField(max_length=100)),
                ('progr_podg', models.CharField(max_length=100)),
                ('obr_std', models.CharField(max_length=20)),
                ('napr_podg_plan', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Kursovaya.Napravlenie')),
            ],
        ),
    ]
