# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-25 16:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Kursovaya', '0007_uch_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chasi',
            fields=[
                ('id_chasi', models.AutoField(primary_key=True, serialize=False)),
                ('kod_discipl', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Kursovaya.Disciplina')),
                ('kod_uch_plan', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Kursovaya.Uch_plan')),
            ],
        ),
    ]
