# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-25 16:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Kursovaya', '0008_chasi'),
    ]

    operations = [
        migrations.AddField(
            model_name='chasi',
            name='discipl_chasi',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Kursovaya.Napravlenie'),
        ),
    ]
