# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-25 16:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Kursovaya', '0009_chasi_discipl_chasi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id_data', models.AutoField(primary_key=True, serialize=False)),
                ('num_para', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Grouppa',
            fields=[
                ('id_group', models.AutoField(primary_key=True, serialize=False)),
                ('name_group', models.CharField(max_length=10)),
                ('chisl', models.IntegerField(default=0)),
                ('form_ob', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Kursovaya.Forma_ob')),
                ('kaf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Kursovaya.Kafedra')),
                ('napravl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Kursovaya.Napravlenie')),
            ],
        ),
        migrations.AddField(
            model_name='data',
            name='num_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Kursovaya.Grouppa'),
        ),
    ]
