# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-28 00:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Kursovaya', '0010_auto_20180525_1921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uch_plan',
            name='napr_podg_plan',
        ),
        migrations.AlterField(
            model_name='uch_plan',
            name='progr_podg',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Kursovaya.Napravlenie'),
        ),
    ]
