# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-28 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kursovaya', '0011_auto_20180528_0341'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='chislo',
            field=models.DateField(blank=True, default='2018-05-28'),
            preserve_default=False,
        ),
    ]
